server:
  port: 8080

spring:
  profiles:
    active: secure
  ai:
    openai:
      api-key: "apikey"
      base-url: "url"
      chat:
        options:
          model: "model"

springdoc:
  show-actuator: false
  swagger-ui:
    enabled: true
    path: /swagger-ui.html