server:
  port: 8080

spring:
  profiles:
    active: secure
  ai:
    openai:
      api-key: ${AI_API_KEY:aiapikey}
      base-url: ${AI_API_URL:aiapiurl}
      chat:
        options:
          model: ${AI_MODEL:aimodel}

telegram:
  token: ${TELEGRAM_TOKEN:telegram_token}
  name: ${TELEGRAM_BOT_NAME:telegram_name}


springdoc:
  show-actuator: false
  swagger-ui:
    enabled: true
    path: /swagger-ui.html